######
## This file contains global replacements variable that can re-used accross the configuration files
## Every value should be reviewed and properly customized as part of your initial installation
## Refer to the documentation for available options:
## https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/working-with-solution-specific-variables.html#parameter-store-reference-variable
## https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.ParameterReplacementConfigV2.html
######
globalReplacements:
  # Home Region
  - key: AcceleratorHomeRegion
    type: String
    value: us-east-2
  # Security notification emails
  - key: SecurityHigh
    type: String
    value: jitc-high@joelinthecloud.com
  - key: SecurityMedium
    type: String
    value: jitc-medium@joelinthecloud.com
  - key: SecurityLow
    type: String
    value: jitc-low@joelinthecloud.com
  # Budget notification emails
  - key: BudgetEmail
    type: String
    value: jitc-budget@joelinthecloud.com
